/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as HostImport } from './routes/host'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as HostOrganizationsIndexImport } from './routes/host/organizations/index'
import { Route as HostOrganizationsOrganizationImport } from './routes/host/organizations/$organization'
import { Route as HostContestsContestImport } from './routes/host/contests/$contest'
import { Route as HostOrganizationsOrganizationIndexImport } from './routes/host/organizations/$organization.index'
import { Route as HostOrganizationsOrganizationMembersImport } from './routes/host/organizations/$organization.members'
import { Route as HostOrganizationsOrganizationContestsImport } from './routes/host/organizations/$organization.contests'
import { Route as HostContestsContestEntriesImport } from './routes/host/contests/$contest.entries'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const HostRoute = HostImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HostOrganizationsIndexRoute = HostOrganizationsIndexImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => HostRoute,
} as any)

const HostOrganizationsOrganizationRoute =
  HostOrganizationsOrganizationImport.update({
    id: '/organizations/$organization',
    path: '/organizations/$organization',
    getParentRoute: () => HostRoute,
  } as any)

const HostContestsContestRoute = HostContestsContestImport.update({
  id: '/contests/$contest',
  path: '/contests/$contest',
  getParentRoute: () => HostRoute,
} as any)

const HostOrganizationsOrganizationIndexRoute =
  HostOrganizationsOrganizationIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => HostOrganizationsOrganizationRoute,
  } as any)

const HostOrganizationsOrganizationMembersRoute =
  HostOrganizationsOrganizationMembersImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => HostOrganizationsOrganizationRoute,
  } as any)

const HostOrganizationsOrganizationContestsRoute =
  HostOrganizationsOrganizationContestsImport.update({
    id: '/contests',
    path: '/contests',
    getParentRoute: () => HostOrganizationsOrganizationRoute,
  } as any)

const HostContestsContestEntriesRoute = HostContestsContestEntriesImport.update(
  {
    id: '/entries',
    path: '/entries',
    getParentRoute: () => HostContestsContestRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/host/contests/$contest': {
      id: '/host/contests/$contest'
      path: '/contests/$contest'
      fullPath: '/host/contests/$contest'
      preLoaderRoute: typeof HostContestsContestImport
      parentRoute: typeof HostImport
    }
    '/host/organizations/$organization': {
      id: '/host/organizations/$organization'
      path: '/organizations/$organization'
      fullPath: '/host/organizations/$organization'
      preLoaderRoute: typeof HostOrganizationsOrganizationImport
      parentRoute: typeof HostImport
    }
    '/host/organizations/': {
      id: '/host/organizations/'
      path: '/organizations'
      fullPath: '/host/organizations'
      preLoaderRoute: typeof HostOrganizationsIndexImport
      parentRoute: typeof HostImport
    }
    '/host/contests/$contest/entries': {
      id: '/host/contests/$contest/entries'
      path: '/entries'
      fullPath: '/host/contests/$contest/entries'
      preLoaderRoute: typeof HostContestsContestEntriesImport
      parentRoute: typeof HostContestsContestImport
    }
    '/host/organizations/$organization/contests': {
      id: '/host/organizations/$organization/contests'
      path: '/contests'
      fullPath: '/host/organizations/$organization/contests'
      preLoaderRoute: typeof HostOrganizationsOrganizationContestsImport
      parentRoute: typeof HostOrganizationsOrganizationImport
    }
    '/host/organizations/$organization/members': {
      id: '/host/organizations/$organization/members'
      path: '/members'
      fullPath: '/host/organizations/$organization/members'
      preLoaderRoute: typeof HostOrganizationsOrganizationMembersImport
      parentRoute: typeof HostOrganizationsOrganizationImport
    }
    '/host/organizations/$organization/': {
      id: '/host/organizations/$organization/'
      path: '/'
      fullPath: '/host/organizations/$organization/'
      preLoaderRoute: typeof HostOrganizationsOrganizationIndexImport
      parentRoute: typeof HostOrganizationsOrganizationImport
    }
  }
}

// Create and export the route tree

interface HostContestsContestRouteChildren {
  HostContestsContestEntriesRoute: typeof HostContestsContestEntriesRoute
}

const HostContestsContestRouteChildren: HostContestsContestRouteChildren = {
  HostContestsContestEntriesRoute: HostContestsContestEntriesRoute,
}

const HostContestsContestRouteWithChildren =
  HostContestsContestRoute._addFileChildren(HostContestsContestRouteChildren)

interface HostOrganizationsOrganizationRouteChildren {
  HostOrganizationsOrganizationContestsRoute: typeof HostOrganizationsOrganizationContestsRoute
  HostOrganizationsOrganizationMembersRoute: typeof HostOrganizationsOrganizationMembersRoute
  HostOrganizationsOrganizationIndexRoute: typeof HostOrganizationsOrganizationIndexRoute
}

const HostOrganizationsOrganizationRouteChildren: HostOrganizationsOrganizationRouteChildren =
  {
    HostOrganizationsOrganizationContestsRoute:
      HostOrganizationsOrganizationContestsRoute,
    HostOrganizationsOrganizationMembersRoute:
      HostOrganizationsOrganizationMembersRoute,
    HostOrganizationsOrganizationIndexRoute:
      HostOrganizationsOrganizationIndexRoute,
  }

const HostOrganizationsOrganizationRouteWithChildren =
  HostOrganizationsOrganizationRoute._addFileChildren(
    HostOrganizationsOrganizationRouteChildren,
  )

interface HostRouteChildren {
  HostContestsContestRoute: typeof HostContestsContestRouteWithChildren
  HostOrganizationsOrganizationRoute: typeof HostOrganizationsOrganizationRouteWithChildren
  HostOrganizationsIndexRoute: typeof HostOrganizationsIndexRoute
}

const HostRouteChildren: HostRouteChildren = {
  HostContestsContestRoute: HostContestsContestRouteWithChildren,
  HostOrganizationsOrganizationRoute:
    HostOrganizationsOrganizationRouteWithChildren,
  HostOrganizationsIndexRoute: HostOrganizationsIndexRoute,
}

const HostRouteWithChildren = HostRoute._addFileChildren(HostRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/host': typeof HostRouteWithChildren
  '/login': typeof LoginRoute
  '/host/contests/$contest': typeof HostContestsContestRouteWithChildren
  '/host/organizations/$organization': typeof HostOrganizationsOrganizationRouteWithChildren
  '/host/organizations': typeof HostOrganizationsIndexRoute
  '/host/contests/$contest/entries': typeof HostContestsContestEntriesRoute
  '/host/organizations/$organization/contests': typeof HostOrganizationsOrganizationContestsRoute
  '/host/organizations/$organization/members': typeof HostOrganizationsOrganizationMembersRoute
  '/host/organizations/$organization/': typeof HostOrganizationsOrganizationIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/host': typeof HostRouteWithChildren
  '/login': typeof LoginRoute
  '/host/contests/$contest': typeof HostContestsContestRouteWithChildren
  '/host/organizations': typeof HostOrganizationsIndexRoute
  '/host/contests/$contest/entries': typeof HostContestsContestEntriesRoute
  '/host/organizations/$organization/contests': typeof HostOrganizationsOrganizationContestsRoute
  '/host/organizations/$organization/members': typeof HostOrganizationsOrganizationMembersRoute
  '/host/organizations/$organization': typeof HostOrganizationsOrganizationIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/host': typeof HostRouteWithChildren
  '/login': typeof LoginRoute
  '/host/contests/$contest': typeof HostContestsContestRouteWithChildren
  '/host/organizations/$organization': typeof HostOrganizationsOrganizationRouteWithChildren
  '/host/organizations/': typeof HostOrganizationsIndexRoute
  '/host/contests/$contest/entries': typeof HostContestsContestEntriesRoute
  '/host/organizations/$organization/contests': typeof HostOrganizationsOrganizationContestsRoute
  '/host/organizations/$organization/members': typeof HostOrganizationsOrganizationMembersRoute
  '/host/organizations/$organization/': typeof HostOrganizationsOrganizationIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/host'
    | '/login'
    | '/host/contests/$contest'
    | '/host/organizations/$organization'
    | '/host/organizations'
    | '/host/contests/$contest/entries'
    | '/host/organizations/$organization/contests'
    | '/host/organizations/$organization/members'
    | '/host/organizations/$organization/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/host'
    | '/login'
    | '/host/contests/$contest'
    | '/host/organizations'
    | '/host/contests/$contest/entries'
    | '/host/organizations/$organization/contests'
    | '/host/organizations/$organization/members'
    | '/host/organizations/$organization'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/host'
    | '/login'
    | '/host/contests/$contest'
    | '/host/organizations/$organization'
    | '/host/organizations/'
    | '/host/contests/$contest/entries'
    | '/host/organizations/$organization/contests'
    | '/host/organizations/$organization/members'
    | '/host/organizations/$organization/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HostRoute: typeof HostRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HostRoute: HostRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/host",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/host": {
      "filePath": "host.tsx",
      "children": [
        "/host/contests/$contest",
        "/host/organizations/$organization",
        "/host/organizations/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/host/contests/$contest": {
      "filePath": "host/contests/$contest.tsx",
      "parent": "/host",
      "children": [
        "/host/contests/$contest/entries"
      ]
    },
    "/host/organizations/$organization": {
      "filePath": "host/organizations/$organization.tsx",
      "parent": "/host",
      "children": [
        "/host/organizations/$organization/contests",
        "/host/organizations/$organization/members",
        "/host/organizations/$organization/"
      ]
    },
    "/host/organizations/": {
      "filePath": "host/organizations/index.tsx",
      "parent": "/host"
    },
    "/host/contests/$contest/entries": {
      "filePath": "host/contests/$contest.entries.tsx",
      "parent": "/host/contests/$contest"
    },
    "/host/organizations/$organization/contests": {
      "filePath": "host/organizations/$organization.contests.tsx",
      "parent": "/host/organizations/$organization"
    },
    "/host/organizations/$organization/members": {
      "filePath": "host/organizations/$organization.members.tsx",
      "parent": "/host/organizations/$organization"
    },
    "/host/organizations/$organization/": {
      "filePath": "host/organizations/$organization.index.tsx",
      "parent": "/host/organizations/$organization"
    }
  }
}
ROUTE_MANIFEST_END */
