/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as HostImport } from './routes/host'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as HostOrganizationsOrganizationImport } from './routes/host/organizations/$organization'
import { Route as HostContestsContestImport } from './routes/host/contests/$contest'
import { Route as HostOrganizationsOrganizationContestsImport } from './routes/host/organizations/$organization.contests'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const HostRoute = HostImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HostOrganizationsOrganizationRoute =
  HostOrganizationsOrganizationImport.update({
    id: '/organizations/$organization',
    path: '/organizations/$organization',
    getParentRoute: () => HostRoute,
  } as any)

const HostContestsContestRoute = HostContestsContestImport.update({
  id: '/contests/$contest',
  path: '/contests/$contest',
  getParentRoute: () => HostRoute,
} as any)

const HostOrganizationsOrganizationContestsRoute =
  HostOrganizationsOrganizationContestsImport.update({
    id: '/contests',
    path: '/contests',
    getParentRoute: () => HostOrganizationsOrganizationRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/host/contests/$contest': {
      id: '/host/contests/$contest'
      path: '/contests/$contest'
      fullPath: '/host/contests/$contest'
      preLoaderRoute: typeof HostContestsContestImport
      parentRoute: typeof HostImport
    }
    '/host/organizations/$organization': {
      id: '/host/organizations/$organization'
      path: '/organizations/$organization'
      fullPath: '/host/organizations/$organization'
      preLoaderRoute: typeof HostOrganizationsOrganizationImport
      parentRoute: typeof HostImport
    }
    '/host/organizations/$organization/contests': {
      id: '/host/organizations/$organization/contests'
      path: '/contests'
      fullPath: '/host/organizations/$organization/contests'
      preLoaderRoute: typeof HostOrganizationsOrganizationContestsImport
      parentRoute: typeof HostOrganizationsOrganizationImport
    }
  }
}

// Create and export the route tree

interface HostOrganizationsOrganizationRouteChildren {
  HostOrganizationsOrganizationContestsRoute: typeof HostOrganizationsOrganizationContestsRoute
}

const HostOrganizationsOrganizationRouteChildren: HostOrganizationsOrganizationRouteChildren =
  {
    HostOrganizationsOrganizationContestsRoute:
      HostOrganizationsOrganizationContestsRoute,
  }

const HostOrganizationsOrganizationRouteWithChildren =
  HostOrganizationsOrganizationRoute._addFileChildren(
    HostOrganizationsOrganizationRouteChildren,
  )

interface HostRouteChildren {
  HostContestsContestRoute: typeof HostContestsContestRoute
  HostOrganizationsOrganizationRoute: typeof HostOrganizationsOrganizationRouteWithChildren
}

const HostRouteChildren: HostRouteChildren = {
  HostContestsContestRoute: HostContestsContestRoute,
  HostOrganizationsOrganizationRoute:
    HostOrganizationsOrganizationRouteWithChildren,
}

const HostRouteWithChildren = HostRoute._addFileChildren(HostRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/host': typeof HostRouteWithChildren
  '/login': typeof LoginRoute
  '/host/contests/$contest': typeof HostContestsContestRoute
  '/host/organizations/$organization': typeof HostOrganizationsOrganizationRouteWithChildren
  '/host/organizations/$organization/contests': typeof HostOrganizationsOrganizationContestsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/host': typeof HostRouteWithChildren
  '/login': typeof LoginRoute
  '/host/contests/$contest': typeof HostContestsContestRoute
  '/host/organizations/$organization': typeof HostOrganizationsOrganizationRouteWithChildren
  '/host/organizations/$organization/contests': typeof HostOrganizationsOrganizationContestsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/host': typeof HostRouteWithChildren
  '/login': typeof LoginRoute
  '/host/contests/$contest': typeof HostContestsContestRoute
  '/host/organizations/$organization': typeof HostOrganizationsOrganizationRouteWithChildren
  '/host/organizations/$organization/contests': typeof HostOrganizationsOrganizationContestsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/host'
    | '/login'
    | '/host/contests/$contest'
    | '/host/organizations/$organization'
    | '/host/organizations/$organization/contests'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/host'
    | '/login'
    | '/host/contests/$contest'
    | '/host/organizations/$organization'
    | '/host/organizations/$organization/contests'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/host'
    | '/login'
    | '/host/contests/$contest'
    | '/host/organizations/$organization'
    | '/host/organizations/$organization/contests'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HostRoute: typeof HostRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HostRoute: HostRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/host",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/host": {
      "filePath": "host.tsx",
      "children": [
        "/host/contests/$contest",
        "/host/organizations/$organization"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/host/contests/$contest": {
      "filePath": "host/contests/$contest.tsx",
      "parent": "/host"
    },
    "/host/organizations/$organization": {
      "filePath": "host/organizations/$organization.tsx",
      "parent": "/host",
      "children": [
        "/host/organizations/$organization/contests"
      ]
    },
    "/host/organizations/$organization/contests": {
      "filePath": "host/organizations/$organization.contests.tsx",
      "parent": "/host/organizations/$organization"
    }
  }
}
ROUTE_MANIFEST_END */
