/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as HostImport } from './routes/host'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as HostProfileImport } from './routes/host/profile'
import { Route as HostOrganizationsImport } from './routes/host/organizations'
import { Route as HostOrganizationsIndexImport } from './routes/host/organizations/index'
import { Route as HostOrganizationsOrganizationImport } from './routes/host/organizations/$organization'
import { Route as HostOrganizationsOrganizationIndexImport } from './routes/host/organizations/$organization/index'
import { Route as HostOrganizationsOrganizationMembersImport } from './routes/host/organizations/$organization/members'
import { Route as HostOrganizationsOrganizationContestsImport } from './routes/host/organizations/$organization/contests'
import { Route as HostOrganizationsOrganizationContestsIndexImport } from './routes/host/organizations/$organization/contests/index'
import { Route as HostOrganizationsOrganizationContestsContestImport } from './routes/host/organizations/$organization/contests/$contest'
import { Route as HostOrganizationsOrganizationContestsContestEntriesImport } from './routes/host/organizations/$organization/contests/$contest/entries'
import { Route as HostOrganizationsOrganizationContestsContestDashboardImport } from './routes/host/organizations/$organization/contests/$contest/dashboard'
import { Route as HostOrganizationsOrganizationContestsContestConfigureImport } from './routes/host/organizations/$organization/contests/$contest/configure'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const HostRoute = HostImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HostProfileRoute = HostProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => HostRoute,
} as any)

const HostOrganizationsRoute = HostOrganizationsImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => HostRoute,
} as any)

const HostOrganizationsIndexRoute = HostOrganizationsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HostOrganizationsRoute,
} as any)

const HostOrganizationsOrganizationRoute =
  HostOrganizationsOrganizationImport.update({
    id: '/$organization',
    path: '/$organization',
    getParentRoute: () => HostOrganizationsRoute,
  } as any)

const HostOrganizationsOrganizationIndexRoute =
  HostOrganizationsOrganizationIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => HostOrganizationsOrganizationRoute,
  } as any)

const HostOrganizationsOrganizationMembersRoute =
  HostOrganizationsOrganizationMembersImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => HostOrganizationsOrganizationRoute,
  } as any)

const HostOrganizationsOrganizationContestsRoute =
  HostOrganizationsOrganizationContestsImport.update({
    id: '/contests',
    path: '/contests',
    getParentRoute: () => HostOrganizationsOrganizationRoute,
  } as any)

const HostOrganizationsOrganizationContestsIndexRoute =
  HostOrganizationsOrganizationContestsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => HostOrganizationsOrganizationContestsRoute,
  } as any)

const HostOrganizationsOrganizationContestsContestRoute =
  HostOrganizationsOrganizationContestsContestImport.update({
    id: '/$contest',
    path: '/$contest',
    getParentRoute: () => HostOrganizationsOrganizationContestsRoute,
  } as any)

const HostOrganizationsOrganizationContestsContestEntriesRoute =
  HostOrganizationsOrganizationContestsContestEntriesImport.update({
    id: '/entries',
    path: '/entries',
    getParentRoute: () => HostOrganizationsOrganizationContestsContestRoute,
  } as any)

const HostOrganizationsOrganizationContestsContestDashboardRoute =
  HostOrganizationsOrganizationContestsContestDashboardImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => HostOrganizationsOrganizationContestsContestRoute,
  } as any)

const HostOrganizationsOrganizationContestsContestConfigureRoute =
  HostOrganizationsOrganizationContestsContestConfigureImport.update({
    id: '/configure',
    path: '/configure',
    getParentRoute: () => HostOrganizationsOrganizationContestsContestRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/host/organizations': {
      id: '/host/organizations'
      path: '/organizations'
      fullPath: '/host/organizations'
      preLoaderRoute: typeof HostOrganizationsImport
      parentRoute: typeof HostImport
    }
    '/host/profile': {
      id: '/host/profile'
      path: '/profile'
      fullPath: '/host/profile'
      preLoaderRoute: typeof HostProfileImport
      parentRoute: typeof HostImport
    }
    '/host/organizations/$organization': {
      id: '/host/organizations/$organization'
      path: '/$organization'
      fullPath: '/host/organizations/$organization'
      preLoaderRoute: typeof HostOrganizationsOrganizationImport
      parentRoute: typeof HostOrganizationsImport
    }
    '/host/organizations/': {
      id: '/host/organizations/'
      path: '/'
      fullPath: '/host/organizations/'
      preLoaderRoute: typeof HostOrganizationsIndexImport
      parentRoute: typeof HostOrganizationsImport
    }
    '/host/organizations/$organization/contests': {
      id: '/host/organizations/$organization/contests'
      path: '/contests'
      fullPath: '/host/organizations/$organization/contests'
      preLoaderRoute: typeof HostOrganizationsOrganizationContestsImport
      parentRoute: typeof HostOrganizationsOrganizationImport
    }
    '/host/organizations/$organization/members': {
      id: '/host/organizations/$organization/members'
      path: '/members'
      fullPath: '/host/organizations/$organization/members'
      preLoaderRoute: typeof HostOrganizationsOrganizationMembersImport
      parentRoute: typeof HostOrganizationsOrganizationImport
    }
    '/host/organizations/$organization/': {
      id: '/host/organizations/$organization/'
      path: '/'
      fullPath: '/host/organizations/$organization/'
      preLoaderRoute: typeof HostOrganizationsOrganizationIndexImport
      parentRoute: typeof HostOrganizationsOrganizationImport
    }
    '/host/organizations/$organization/contests/$contest': {
      id: '/host/organizations/$organization/contests/$contest'
      path: '/$contest'
      fullPath: '/host/organizations/$organization/contests/$contest'
      preLoaderRoute: typeof HostOrganizationsOrganizationContestsContestImport
      parentRoute: typeof HostOrganizationsOrganizationContestsImport
    }
    '/host/organizations/$organization/contests/': {
      id: '/host/organizations/$organization/contests/'
      path: '/'
      fullPath: '/host/organizations/$organization/contests/'
      preLoaderRoute: typeof HostOrganizationsOrganizationContestsIndexImport
      parentRoute: typeof HostOrganizationsOrganizationContestsImport
    }
    '/host/organizations/$organization/contests/$contest/configure': {
      id: '/host/organizations/$organization/contests/$contest/configure'
      path: '/configure'
      fullPath: '/host/organizations/$organization/contests/$contest/configure'
      preLoaderRoute: typeof HostOrganizationsOrganizationContestsContestConfigureImport
      parentRoute: typeof HostOrganizationsOrganizationContestsContestImport
    }
    '/host/organizations/$organization/contests/$contest/dashboard': {
      id: '/host/organizations/$organization/contests/$contest/dashboard'
      path: '/dashboard'
      fullPath: '/host/organizations/$organization/contests/$contest/dashboard'
      preLoaderRoute: typeof HostOrganizationsOrganizationContestsContestDashboardImport
      parentRoute: typeof HostOrganizationsOrganizationContestsContestImport
    }
    '/host/organizations/$organization/contests/$contest/entries': {
      id: '/host/organizations/$organization/contests/$contest/entries'
      path: '/entries'
      fullPath: '/host/organizations/$organization/contests/$contest/entries'
      preLoaderRoute: typeof HostOrganizationsOrganizationContestsContestEntriesImport
      parentRoute: typeof HostOrganizationsOrganizationContestsContestImport
    }
  }
}

// Create and export the route tree

interface HostOrganizationsOrganizationContestsContestRouteChildren {
  HostOrganizationsOrganizationContestsContestConfigureRoute: typeof HostOrganizationsOrganizationContestsContestConfigureRoute
  HostOrganizationsOrganizationContestsContestDashboardRoute: typeof HostOrganizationsOrganizationContestsContestDashboardRoute
  HostOrganizationsOrganizationContestsContestEntriesRoute: typeof HostOrganizationsOrganizationContestsContestEntriesRoute
}

const HostOrganizationsOrganizationContestsContestRouteChildren: HostOrganizationsOrganizationContestsContestRouteChildren =
  {
    HostOrganizationsOrganizationContestsContestConfigureRoute:
      HostOrganizationsOrganizationContestsContestConfigureRoute,
    HostOrganizationsOrganizationContestsContestDashboardRoute:
      HostOrganizationsOrganizationContestsContestDashboardRoute,
    HostOrganizationsOrganizationContestsContestEntriesRoute:
      HostOrganizationsOrganizationContestsContestEntriesRoute,
  }

const HostOrganizationsOrganizationContestsContestRouteWithChildren =
  HostOrganizationsOrganizationContestsContestRoute._addFileChildren(
    HostOrganizationsOrganizationContestsContestRouteChildren,
  )

interface HostOrganizationsOrganizationContestsRouteChildren {
  HostOrganizationsOrganizationContestsContestRoute: typeof HostOrganizationsOrganizationContestsContestRouteWithChildren
  HostOrganizationsOrganizationContestsIndexRoute: typeof HostOrganizationsOrganizationContestsIndexRoute
}

const HostOrganizationsOrganizationContestsRouteChildren: HostOrganizationsOrganizationContestsRouteChildren =
  {
    HostOrganizationsOrganizationContestsContestRoute:
      HostOrganizationsOrganizationContestsContestRouteWithChildren,
    HostOrganizationsOrganizationContestsIndexRoute:
      HostOrganizationsOrganizationContestsIndexRoute,
  }

const HostOrganizationsOrganizationContestsRouteWithChildren =
  HostOrganizationsOrganizationContestsRoute._addFileChildren(
    HostOrganizationsOrganizationContestsRouteChildren,
  )

interface HostOrganizationsOrganizationRouteChildren {
  HostOrganizationsOrganizationContestsRoute: typeof HostOrganizationsOrganizationContestsRouteWithChildren
  HostOrganizationsOrganizationMembersRoute: typeof HostOrganizationsOrganizationMembersRoute
  HostOrganizationsOrganizationIndexRoute: typeof HostOrganizationsOrganizationIndexRoute
}

const HostOrganizationsOrganizationRouteChildren: HostOrganizationsOrganizationRouteChildren =
  {
    HostOrganizationsOrganizationContestsRoute:
      HostOrganizationsOrganizationContestsRouteWithChildren,
    HostOrganizationsOrganizationMembersRoute:
      HostOrganizationsOrganizationMembersRoute,
    HostOrganizationsOrganizationIndexRoute:
      HostOrganizationsOrganizationIndexRoute,
  }

const HostOrganizationsOrganizationRouteWithChildren =
  HostOrganizationsOrganizationRoute._addFileChildren(
    HostOrganizationsOrganizationRouteChildren,
  )

interface HostOrganizationsRouteChildren {
  HostOrganizationsOrganizationRoute: typeof HostOrganizationsOrganizationRouteWithChildren
  HostOrganizationsIndexRoute: typeof HostOrganizationsIndexRoute
}

const HostOrganizationsRouteChildren: HostOrganizationsRouteChildren = {
  HostOrganizationsOrganizationRoute:
    HostOrganizationsOrganizationRouteWithChildren,
  HostOrganizationsIndexRoute: HostOrganizationsIndexRoute,
}

const HostOrganizationsRouteWithChildren =
  HostOrganizationsRoute._addFileChildren(HostOrganizationsRouteChildren)

interface HostRouteChildren {
  HostOrganizationsRoute: typeof HostOrganizationsRouteWithChildren
  HostProfileRoute: typeof HostProfileRoute
}

const HostRouteChildren: HostRouteChildren = {
  HostOrganizationsRoute: HostOrganizationsRouteWithChildren,
  HostProfileRoute: HostProfileRoute,
}

const HostRouteWithChildren = HostRoute._addFileChildren(HostRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/host': typeof HostRouteWithChildren
  '/login': typeof LoginRoute
  '/host/organizations': typeof HostOrganizationsRouteWithChildren
  '/host/profile': typeof HostProfileRoute
  '/host/organizations/$organization': typeof HostOrganizationsOrganizationRouteWithChildren
  '/host/organizations/': typeof HostOrganizationsIndexRoute
  '/host/organizations/$organization/contests': typeof HostOrganizationsOrganizationContestsRouteWithChildren
  '/host/organizations/$organization/members': typeof HostOrganizationsOrganizationMembersRoute
  '/host/organizations/$organization/': typeof HostOrganizationsOrganizationIndexRoute
  '/host/organizations/$organization/contests/$contest': typeof HostOrganizationsOrganizationContestsContestRouteWithChildren
  '/host/organizations/$organization/contests/': typeof HostOrganizationsOrganizationContestsIndexRoute
  '/host/organizations/$organization/contests/$contest/configure': typeof HostOrganizationsOrganizationContestsContestConfigureRoute
  '/host/organizations/$organization/contests/$contest/dashboard': typeof HostOrganizationsOrganizationContestsContestDashboardRoute
  '/host/organizations/$organization/contests/$contest/entries': typeof HostOrganizationsOrganizationContestsContestEntriesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/host': typeof HostRouteWithChildren
  '/login': typeof LoginRoute
  '/host/profile': typeof HostProfileRoute
  '/host/organizations': typeof HostOrganizationsIndexRoute
  '/host/organizations/$organization/members': typeof HostOrganizationsOrganizationMembersRoute
  '/host/organizations/$organization': typeof HostOrganizationsOrganizationIndexRoute
  '/host/organizations/$organization/contests/$contest': typeof HostOrganizationsOrganizationContestsContestRouteWithChildren
  '/host/organizations/$organization/contests': typeof HostOrganizationsOrganizationContestsIndexRoute
  '/host/organizations/$organization/contests/$contest/configure': typeof HostOrganizationsOrganizationContestsContestConfigureRoute
  '/host/organizations/$organization/contests/$contest/dashboard': typeof HostOrganizationsOrganizationContestsContestDashboardRoute
  '/host/organizations/$organization/contests/$contest/entries': typeof HostOrganizationsOrganizationContestsContestEntriesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/host': typeof HostRouteWithChildren
  '/login': typeof LoginRoute
  '/host/organizations': typeof HostOrganizationsRouteWithChildren
  '/host/profile': typeof HostProfileRoute
  '/host/organizations/$organization': typeof HostOrganizationsOrganizationRouteWithChildren
  '/host/organizations/': typeof HostOrganizationsIndexRoute
  '/host/organizations/$organization/contests': typeof HostOrganizationsOrganizationContestsRouteWithChildren
  '/host/organizations/$organization/members': typeof HostOrganizationsOrganizationMembersRoute
  '/host/organizations/$organization/': typeof HostOrganizationsOrganizationIndexRoute
  '/host/organizations/$organization/contests/$contest': typeof HostOrganizationsOrganizationContestsContestRouteWithChildren
  '/host/organizations/$organization/contests/': typeof HostOrganizationsOrganizationContestsIndexRoute
  '/host/organizations/$organization/contests/$contest/configure': typeof HostOrganizationsOrganizationContestsContestConfigureRoute
  '/host/organizations/$organization/contests/$contest/dashboard': typeof HostOrganizationsOrganizationContestsContestDashboardRoute
  '/host/organizations/$organization/contests/$contest/entries': typeof HostOrganizationsOrganizationContestsContestEntriesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/host'
    | '/login'
    | '/host/organizations'
    | '/host/profile'
    | '/host/organizations/$organization'
    | '/host/organizations/'
    | '/host/organizations/$organization/contests'
    | '/host/organizations/$organization/members'
    | '/host/organizations/$organization/'
    | '/host/organizations/$organization/contests/$contest'
    | '/host/organizations/$organization/contests/'
    | '/host/organizations/$organization/contests/$contest/configure'
    | '/host/organizations/$organization/contests/$contest/dashboard'
    | '/host/organizations/$organization/contests/$contest/entries'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/host'
    | '/login'
    | '/host/profile'
    | '/host/organizations'
    | '/host/organizations/$organization/members'
    | '/host/organizations/$organization'
    | '/host/organizations/$organization/contests/$contest'
    | '/host/organizations/$organization/contests'
    | '/host/organizations/$organization/contests/$contest/configure'
    | '/host/organizations/$organization/contests/$contest/dashboard'
    | '/host/organizations/$organization/contests/$contest/entries'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/host'
    | '/login'
    | '/host/organizations'
    | '/host/profile'
    | '/host/organizations/$organization'
    | '/host/organizations/'
    | '/host/organizations/$organization/contests'
    | '/host/organizations/$organization/members'
    | '/host/organizations/$organization/'
    | '/host/organizations/$organization/contests/$contest'
    | '/host/organizations/$organization/contests/'
    | '/host/organizations/$organization/contests/$contest/configure'
    | '/host/organizations/$organization/contests/$contest/dashboard'
    | '/host/organizations/$organization/contests/$contest/entries'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HostRoute: typeof HostRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HostRoute: HostRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/host",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/host": {
      "filePath": "host.tsx",
      "children": [
        "/host/organizations",
        "/host/profile"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/host/organizations": {
      "filePath": "host/organizations.tsx",
      "parent": "/host",
      "children": [
        "/host/organizations/$organization",
        "/host/organizations/"
      ]
    },
    "/host/profile": {
      "filePath": "host/profile.tsx",
      "parent": "/host"
    },
    "/host/organizations/$organization": {
      "filePath": "host/organizations/$organization.tsx",
      "parent": "/host/organizations",
      "children": [
        "/host/organizations/$organization/contests",
        "/host/organizations/$organization/members",
        "/host/organizations/$organization/"
      ]
    },
    "/host/organizations/": {
      "filePath": "host/organizations/index.tsx",
      "parent": "/host/organizations"
    },
    "/host/organizations/$organization/contests": {
      "filePath": "host/organizations/$organization/contests.tsx",
      "parent": "/host/organizations/$organization",
      "children": [
        "/host/organizations/$organization/contests/$contest",
        "/host/organizations/$organization/contests/"
      ]
    },
    "/host/organizations/$organization/members": {
      "filePath": "host/organizations/$organization/members.tsx",
      "parent": "/host/organizations/$organization"
    },
    "/host/organizations/$organization/": {
      "filePath": "host/organizations/$organization/index.tsx",
      "parent": "/host/organizations/$organization"
    },
    "/host/organizations/$organization/contests/$contest": {
      "filePath": "host/organizations/$organization/contests/$contest.tsx",
      "parent": "/host/organizations/$organization/contests",
      "children": [
        "/host/organizations/$organization/contests/$contest/configure",
        "/host/organizations/$organization/contests/$contest/dashboard",
        "/host/organizations/$organization/contests/$contest/entries"
      ]
    },
    "/host/organizations/$organization/contests/": {
      "filePath": "host/organizations/$organization/contests/index.tsx",
      "parent": "/host/organizations/$organization/contests"
    },
    "/host/organizations/$organization/contests/$contest/configure": {
      "filePath": "host/organizations/$organization/contests/$contest/configure.tsx",
      "parent": "/host/organizations/$organization/contests/$contest"
    },
    "/host/organizations/$organization/contests/$contest/dashboard": {
      "filePath": "host/organizations/$organization/contests/$contest/dashboard.tsx",
      "parent": "/host/organizations/$organization/contests/$contest"
    },
    "/host/organizations/$organization/contests/$contest/entries": {
      "filePath": "host/organizations/$organization/contests/$contest/entries.tsx",
      "parent": "/host/organizations/$organization/contests/$contest"
    }
  }
}
ROUTE_MANIFEST_END */
