/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/solid-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UserRouteRouteImport } from './routes/user/route'
import { Route as HostRouteRouteImport } from './routes/host/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserProfileRouteImport } from './routes/user/profile'
import { Route as HostOrgsRouteRouteImport } from './routes/host/orgs/route'
import { Route as HostOrgsNewRouteImport } from './routes/host/orgs/new'
import { Route as HostOrgsOrgSlugRouteRouteImport } from './routes/host/orgs/$orgSlug/route'
import { Route as HostOrgsOrgSlugMembersRouteImport } from './routes/host/orgs/$orgSlug/members'
import { Route as HostOrgsOrgSlugCallsRouteRouteImport } from './routes/host/orgs/$orgSlug/calls/route'
import { Route as HostOrgsOrgSlugCallsIndexRouteImport } from './routes/host/orgs/$orgSlug/calls/index'
import { Route as HostOrgsOrgSlugCallsCallSlugRouteRouteImport } from './routes/host/orgs/$orgSlug/calls/$callSlug/route'
import { Route as HostOrgsOrgSlugCallsCallSlugTeamRouteImport } from './routes/host/orgs/$orgSlug/calls/$callSlug/team'
import { Route as HostOrgsOrgSlugCallsCallSlugEntriesRouteImport } from './routes/host/orgs/$orgSlug/calls/$callSlug/entries'
import { Route as HostOrgsOrgSlugCallsCallSlugDashboardRouteImport } from './routes/host/orgs/$orgSlug/calls/$callSlug/dashboard'
import { Route as HostOrgsOrgSlugCallsCallSlugRoundsIndexRouteImport } from './routes/host/orgs/$orgSlug/calls/$callSlug/rounds/index'
import { Route as HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugRouteRouteImport } from './routes/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/route'
import { Route as HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugJudgingRouteImport } from './routes/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/judging'
import { Route as HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugConfigureRouteImport } from './routes/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/configure'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRouteRoute = UserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRouteRoute = HostRouteRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRouteRoute,
} as any)
const HostOrgsRouteRoute = HostOrgsRouteRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => HostRouteRoute,
} as any)
const HostOrgsNewRoute = HostOrgsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => HostOrgsRouteRoute,
} as any)
const HostOrgsOrgSlugRouteRoute = HostOrgsOrgSlugRouteRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => HostOrgsRouteRoute,
} as any)
const HostOrgsOrgSlugMembersRoute = HostOrgsOrgSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => HostOrgsOrgSlugRouteRoute,
} as any)
const HostOrgsOrgSlugCallsRouteRoute =
  HostOrgsOrgSlugCallsRouteRouteImport.update({
    id: '/calls',
    path: '/calls',
    getParentRoute: () => HostOrgsOrgSlugRouteRoute,
  } as any)
const HostOrgsOrgSlugCallsIndexRoute =
  HostOrgsOrgSlugCallsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => HostOrgsOrgSlugCallsRouteRoute,
  } as any)
const HostOrgsOrgSlugCallsCallSlugRouteRoute =
  HostOrgsOrgSlugCallsCallSlugRouteRouteImport.update({
    id: '/$callSlug',
    path: '/$callSlug',
    getParentRoute: () => HostOrgsOrgSlugCallsRouteRoute,
  } as any)
const HostOrgsOrgSlugCallsCallSlugTeamRoute =
  HostOrgsOrgSlugCallsCallSlugTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => HostOrgsOrgSlugCallsCallSlugRouteRoute,
  } as any)
const HostOrgsOrgSlugCallsCallSlugEntriesRoute =
  HostOrgsOrgSlugCallsCallSlugEntriesRouteImport.update({
    id: '/entries',
    path: '/entries',
    getParentRoute: () => HostOrgsOrgSlugCallsCallSlugRouteRoute,
  } as any)
const HostOrgsOrgSlugCallsCallSlugDashboardRoute =
  HostOrgsOrgSlugCallsCallSlugDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => HostOrgsOrgSlugCallsCallSlugRouteRoute,
  } as any)
const HostOrgsOrgSlugCallsCallSlugRoundsIndexRoute =
  HostOrgsOrgSlugCallsCallSlugRoundsIndexRouteImport.update({
    id: '/rounds/',
    path: '/rounds/',
    getParentRoute: () => HostOrgsOrgSlugCallsCallSlugRouteRoute,
  } as any)
const HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugRouteRoute =
  HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugRouteRouteImport.update({
    id: '/rounds/$roundSlug',
    path: '/rounds/$roundSlug',
    getParentRoute: () => HostOrgsOrgSlugCallsCallSlugRouteRoute,
  } as any)
const HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugJudgingRoute =
  HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugJudgingRouteImport.update({
    id: '/judging',
    path: '/judging',
    getParentRoute: () => HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugRouteRoute,
  } as any)
const HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugConfigureRoute =
  HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugConfigureRouteImport.update({
    id: '/configure',
    path: '/configure',
    getParentRoute: () => HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/host': typeof HostRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/host/orgs': typeof HostOrgsRouteRouteWithChildren
  '/user/profile': typeof UserProfileRoute
  '/host/orgs/$orgSlug': typeof HostOrgsOrgSlugRouteRouteWithChildren
  '/host/orgs/new': typeof HostOrgsNewRoute
  '/host/orgs/$orgSlug/calls': typeof HostOrgsOrgSlugCallsRouteRouteWithChildren
  '/host/orgs/$orgSlug/members': typeof HostOrgsOrgSlugMembersRoute
  '/host/orgs/$orgSlug/calls/$callSlug': typeof HostOrgsOrgSlugCallsCallSlugRouteRouteWithChildren
  '/host/orgs/$orgSlug/calls/': typeof HostOrgsOrgSlugCallsIndexRoute
  '/host/orgs/$orgSlug/calls/$callSlug/dashboard': typeof HostOrgsOrgSlugCallsCallSlugDashboardRoute
  '/host/orgs/$orgSlug/calls/$callSlug/entries': typeof HostOrgsOrgSlugCallsCallSlugEntriesRoute
  '/host/orgs/$orgSlug/calls/$callSlug/team': typeof HostOrgsOrgSlugCallsCallSlugTeamRoute
  '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug': typeof HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugRouteRouteWithChildren
  '/host/orgs/$orgSlug/calls/$callSlug/rounds': typeof HostOrgsOrgSlugCallsCallSlugRoundsIndexRoute
  '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/configure': typeof HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugConfigureRoute
  '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/judging': typeof HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugJudgingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/host': typeof HostRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/host/orgs': typeof HostOrgsRouteRouteWithChildren
  '/user/profile': typeof UserProfileRoute
  '/host/orgs/$orgSlug': typeof HostOrgsOrgSlugRouteRouteWithChildren
  '/host/orgs/new': typeof HostOrgsNewRoute
  '/host/orgs/$orgSlug/members': typeof HostOrgsOrgSlugMembersRoute
  '/host/orgs/$orgSlug/calls/$callSlug': typeof HostOrgsOrgSlugCallsCallSlugRouteRouteWithChildren
  '/host/orgs/$orgSlug/calls': typeof HostOrgsOrgSlugCallsIndexRoute
  '/host/orgs/$orgSlug/calls/$callSlug/dashboard': typeof HostOrgsOrgSlugCallsCallSlugDashboardRoute
  '/host/orgs/$orgSlug/calls/$callSlug/entries': typeof HostOrgsOrgSlugCallsCallSlugEntriesRoute
  '/host/orgs/$orgSlug/calls/$callSlug/team': typeof HostOrgsOrgSlugCallsCallSlugTeamRoute
  '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug': typeof HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugRouteRouteWithChildren
  '/host/orgs/$orgSlug/calls/$callSlug/rounds': typeof HostOrgsOrgSlugCallsCallSlugRoundsIndexRoute
  '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/configure': typeof HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugConfigureRoute
  '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/judging': typeof HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugJudgingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/host': typeof HostRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/host/orgs': typeof HostOrgsRouteRouteWithChildren
  '/user/profile': typeof UserProfileRoute
  '/host/orgs/$orgSlug': typeof HostOrgsOrgSlugRouteRouteWithChildren
  '/host/orgs/new': typeof HostOrgsNewRoute
  '/host/orgs/$orgSlug/calls': typeof HostOrgsOrgSlugCallsRouteRouteWithChildren
  '/host/orgs/$orgSlug/members': typeof HostOrgsOrgSlugMembersRoute
  '/host/orgs/$orgSlug/calls/$callSlug': typeof HostOrgsOrgSlugCallsCallSlugRouteRouteWithChildren
  '/host/orgs/$orgSlug/calls/': typeof HostOrgsOrgSlugCallsIndexRoute
  '/host/orgs/$orgSlug/calls/$callSlug/dashboard': typeof HostOrgsOrgSlugCallsCallSlugDashboardRoute
  '/host/orgs/$orgSlug/calls/$callSlug/entries': typeof HostOrgsOrgSlugCallsCallSlugEntriesRoute
  '/host/orgs/$orgSlug/calls/$callSlug/team': typeof HostOrgsOrgSlugCallsCallSlugTeamRoute
  '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug': typeof HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugRouteRouteWithChildren
  '/host/orgs/$orgSlug/calls/$callSlug/rounds/': typeof HostOrgsOrgSlugCallsCallSlugRoundsIndexRoute
  '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/configure': typeof HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugConfigureRoute
  '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/judging': typeof HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugJudgingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/host'
    | '/user'
    | '/login'
    | '/host/orgs'
    | '/user/profile'
    | '/host/orgs/$orgSlug'
    | '/host/orgs/new'
    | '/host/orgs/$orgSlug/calls'
    | '/host/orgs/$orgSlug/members'
    | '/host/orgs/$orgSlug/calls/$callSlug'
    | '/host/orgs/$orgSlug/calls/'
    | '/host/orgs/$orgSlug/calls/$callSlug/dashboard'
    | '/host/orgs/$orgSlug/calls/$callSlug/entries'
    | '/host/orgs/$orgSlug/calls/$callSlug/team'
    | '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug'
    | '/host/orgs/$orgSlug/calls/$callSlug/rounds'
    | '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/configure'
    | '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/judging'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/host'
    | '/user'
    | '/login'
    | '/host/orgs'
    | '/user/profile'
    | '/host/orgs/$orgSlug'
    | '/host/orgs/new'
    | '/host/orgs/$orgSlug/members'
    | '/host/orgs/$orgSlug/calls/$callSlug'
    | '/host/orgs/$orgSlug/calls'
    | '/host/orgs/$orgSlug/calls/$callSlug/dashboard'
    | '/host/orgs/$orgSlug/calls/$callSlug/entries'
    | '/host/orgs/$orgSlug/calls/$callSlug/team'
    | '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug'
    | '/host/orgs/$orgSlug/calls/$callSlug/rounds'
    | '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/configure'
    | '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/judging'
  id:
    | '__root__'
    | '/'
    | '/host'
    | '/user'
    | '/login'
    | '/host/orgs'
    | '/user/profile'
    | '/host/orgs/$orgSlug'
    | '/host/orgs/new'
    | '/host/orgs/$orgSlug/calls'
    | '/host/orgs/$orgSlug/members'
    | '/host/orgs/$orgSlug/calls/$callSlug'
    | '/host/orgs/$orgSlug/calls/'
    | '/host/orgs/$orgSlug/calls/$callSlug/dashboard'
    | '/host/orgs/$orgSlug/calls/$callSlug/entries'
    | '/host/orgs/$orgSlug/calls/$callSlug/team'
    | '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug'
    | '/host/orgs/$orgSlug/calls/$callSlug/rounds/'
    | '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/configure'
    | '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/judging'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HostRouteRoute: typeof HostRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/orgs': {
      id: '/host/orgs'
      path: '/orgs'
      fullPath: '/host/orgs'
      preLoaderRoute: typeof HostOrgsRouteRouteImport
      parentRoute: typeof HostRouteRoute
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/host/orgs/$orgSlug': {
      id: '/host/orgs/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/host/orgs/$orgSlug'
      preLoaderRoute: typeof HostOrgsOrgSlugRouteRouteImport
      parentRoute: typeof HostOrgsRouteRoute
    }
    '/host/orgs/new': {
      id: '/host/orgs/new'
      path: '/new'
      fullPath: '/host/orgs/new'
      preLoaderRoute: typeof HostOrgsNewRouteImport
      parentRoute: typeof HostOrgsRouteRoute
    }
    '/host/orgs/$orgSlug/calls': {
      id: '/host/orgs/$orgSlug/calls'
      path: '/calls'
      fullPath: '/host/orgs/$orgSlug/calls'
      preLoaderRoute: typeof HostOrgsOrgSlugCallsRouteRouteImport
      parentRoute: typeof HostOrgsOrgSlugRouteRoute
    }
    '/host/orgs/$orgSlug/members': {
      id: '/host/orgs/$orgSlug/members'
      path: '/members'
      fullPath: '/host/orgs/$orgSlug/members'
      preLoaderRoute: typeof HostOrgsOrgSlugMembersRouteImport
      parentRoute: typeof HostOrgsOrgSlugRouteRoute
    }
    '/host/orgs/$orgSlug/calls/$callSlug': {
      id: '/host/orgs/$orgSlug/calls/$callSlug'
      path: '/$callSlug'
      fullPath: '/host/orgs/$orgSlug/calls/$callSlug'
      preLoaderRoute: typeof HostOrgsOrgSlugCallsCallSlugRouteRouteImport
      parentRoute: typeof HostOrgsOrgSlugCallsRouteRoute
    }
    '/host/orgs/$orgSlug/calls/': {
      id: '/host/orgs/$orgSlug/calls/'
      path: '/'
      fullPath: '/host/orgs/$orgSlug/calls/'
      preLoaderRoute: typeof HostOrgsOrgSlugCallsIndexRouteImport
      parentRoute: typeof HostOrgsOrgSlugCallsRouteRoute
    }
    '/host/orgs/$orgSlug/calls/$callSlug/dashboard': {
      id: '/host/orgs/$orgSlug/calls/$callSlug/dashboard'
      path: '/dashboard'
      fullPath: '/host/orgs/$orgSlug/calls/$callSlug/dashboard'
      preLoaderRoute: typeof HostOrgsOrgSlugCallsCallSlugDashboardRouteImport
      parentRoute: typeof HostOrgsOrgSlugCallsCallSlugRouteRoute
    }
    '/host/orgs/$orgSlug/calls/$callSlug/entries': {
      id: '/host/orgs/$orgSlug/calls/$callSlug/entries'
      path: '/entries'
      fullPath: '/host/orgs/$orgSlug/calls/$callSlug/entries'
      preLoaderRoute: typeof HostOrgsOrgSlugCallsCallSlugEntriesRouteImport
      parentRoute: typeof HostOrgsOrgSlugCallsCallSlugRouteRoute
    }
    '/host/orgs/$orgSlug/calls/$callSlug/team': {
      id: '/host/orgs/$orgSlug/calls/$callSlug/team'
      path: '/team'
      fullPath: '/host/orgs/$orgSlug/calls/$callSlug/team'
      preLoaderRoute: typeof HostOrgsOrgSlugCallsCallSlugTeamRouteImport
      parentRoute: typeof HostOrgsOrgSlugCallsCallSlugRouteRoute
    }
    '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug': {
      id: '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug'
      path: '/rounds/$roundSlug'
      fullPath: '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug'
      preLoaderRoute: typeof HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugRouteRouteImport
      parentRoute: typeof HostOrgsOrgSlugCallsCallSlugRouteRoute
    }
    '/host/orgs/$orgSlug/calls/$callSlug/rounds/': {
      id: '/host/orgs/$orgSlug/calls/$callSlug/rounds/'
      path: '/rounds'
      fullPath: '/host/orgs/$orgSlug/calls/$callSlug/rounds'
      preLoaderRoute: typeof HostOrgsOrgSlugCallsCallSlugRoundsIndexRouteImport
      parentRoute: typeof HostOrgsOrgSlugCallsCallSlugRouteRoute
    }
    '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/configure': {
      id: '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/configure'
      path: '/configure'
      fullPath: '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/configure'
      preLoaderRoute: typeof HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugConfigureRouteImport
      parentRoute: typeof HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugRouteRoute
    }
    '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/judging': {
      id: '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/judging'
      path: '/judging'
      fullPath: '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/judging'
      preLoaderRoute: typeof HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugJudgingRouteImport
      parentRoute: typeof HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugRouteRoute
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/host/route' {
  const createFileRoute: CreateFileRoute<
    '/host',
    FileRoutesByPath['/host']['parentRoute'],
    FileRoutesByPath['/host']['id'],
    FileRoutesByPath['/host']['path'],
    FileRoutesByPath['/host']['fullPath']
  >
}
declare module './routes/user/route' {
  const createFileRoute: CreateFileRoute<
    '/user',
    FileRoutesByPath['/user']['parentRoute'],
    FileRoutesByPath['/user']['id'],
    FileRoutesByPath['/user']['path'],
    FileRoutesByPath['/user']['fullPath']
  >
}
declare module './routes/login' {
  const createFileRoute: CreateFileRoute<
    '/login',
    FileRoutesByPath['/login']['parentRoute'],
    FileRoutesByPath['/login']['id'],
    FileRoutesByPath['/login']['path'],
    FileRoutesByPath['/login']['fullPath']
  >
}
declare module './routes/host/orgs/route' {
  const createFileRoute: CreateFileRoute<
    '/host/orgs',
    FileRoutesByPath['/host/orgs']['parentRoute'],
    FileRoutesByPath['/host/orgs']['id'],
    FileRoutesByPath['/host/orgs']['path'],
    FileRoutesByPath['/host/orgs']['fullPath']
  >
}
declare module './routes/user/profile' {
  const createFileRoute: CreateFileRoute<
    '/user/profile',
    FileRoutesByPath['/user/profile']['parentRoute'],
    FileRoutesByPath['/user/profile']['id'],
    FileRoutesByPath['/user/profile']['path'],
    FileRoutesByPath['/user/profile']['fullPath']
  >
}
declare module './routes/host/orgs/$orgSlug/route' {
  const createFileRoute: CreateFileRoute<
    '/host/orgs/$orgSlug',
    FileRoutesByPath['/host/orgs/$orgSlug']['parentRoute'],
    FileRoutesByPath['/host/orgs/$orgSlug']['id'],
    FileRoutesByPath['/host/orgs/$orgSlug']['path'],
    FileRoutesByPath['/host/orgs/$orgSlug']['fullPath']
  >
}
declare module './routes/host/orgs/new' {
  const createFileRoute: CreateFileRoute<
    '/host/orgs/new',
    FileRoutesByPath['/host/orgs/new']['parentRoute'],
    FileRoutesByPath['/host/orgs/new']['id'],
    FileRoutesByPath['/host/orgs/new']['path'],
    FileRoutesByPath['/host/orgs/new']['fullPath']
  >
}
declare module './routes/host/orgs/$orgSlug/calls/route' {
  const createFileRoute: CreateFileRoute<
    '/host/orgs/$orgSlug/calls',
    FileRoutesByPath['/host/orgs/$orgSlug/calls']['parentRoute'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls']['id'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls']['path'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls']['fullPath']
  >
}
declare module './routes/host/orgs/$orgSlug/members' {
  const createFileRoute: CreateFileRoute<
    '/host/orgs/$orgSlug/members',
    FileRoutesByPath['/host/orgs/$orgSlug/members']['parentRoute'],
    FileRoutesByPath['/host/orgs/$orgSlug/members']['id'],
    FileRoutesByPath['/host/orgs/$orgSlug/members']['path'],
    FileRoutesByPath['/host/orgs/$orgSlug/members']['fullPath']
  >
}
declare module './routes/host/orgs/$orgSlug/calls/$callSlug/route' {
  const createFileRoute: CreateFileRoute<
    '/host/orgs/$orgSlug/calls/$callSlug',
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug']['parentRoute'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug']['id'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug']['path'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug']['fullPath']
  >
}
declare module './routes/host/orgs/$orgSlug/calls/index' {
  const createFileRoute: CreateFileRoute<
    '/host/orgs/$orgSlug/calls/',
    FileRoutesByPath['/host/orgs/$orgSlug/calls/']['parentRoute'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls/']['id'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls/']['path'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls/']['fullPath']
  >
}
declare module './routes/host/orgs/$orgSlug/calls/$callSlug/dashboard' {
  const createFileRoute: CreateFileRoute<
    '/host/orgs/$orgSlug/calls/$callSlug/dashboard',
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/dashboard']['parentRoute'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/dashboard']['id'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/dashboard']['path'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/dashboard']['fullPath']
  >
}
declare module './routes/host/orgs/$orgSlug/calls/$callSlug/entries' {
  const createFileRoute: CreateFileRoute<
    '/host/orgs/$orgSlug/calls/$callSlug/entries',
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/entries']['parentRoute'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/entries']['id'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/entries']['path'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/entries']['fullPath']
  >
}
declare module './routes/host/orgs/$orgSlug/calls/$callSlug/team' {
  const createFileRoute: CreateFileRoute<
    '/host/orgs/$orgSlug/calls/$callSlug/team',
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/team']['parentRoute'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/team']['id'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/team']['path'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/team']['fullPath']
  >
}
declare module './routes/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/route' {
  const createFileRoute: CreateFileRoute<
    '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug',
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug']['parentRoute'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug']['id'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug']['path'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug']['fullPath']
  >
}
declare module './routes/host/orgs/$orgSlug/calls/$callSlug/rounds/index' {
  const createFileRoute: CreateFileRoute<
    '/host/orgs/$orgSlug/calls/$callSlug/rounds/',
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/rounds/']['parentRoute'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/rounds/']['id'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/rounds/']['path'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/rounds/']['fullPath']
  >
}
declare module './routes/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/configure' {
  const createFileRoute: CreateFileRoute<
    '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/configure',
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/configure']['parentRoute'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/configure']['id'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/configure']['path'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/configure']['fullPath']
  >
}
declare module './routes/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/judging' {
  const createFileRoute: CreateFileRoute<
    '/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/judging',
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/judging']['parentRoute'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/judging']['id'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/judging']['path'],
    FileRoutesByPath['/host/orgs/$orgSlug/calls/$callSlug/rounds/$roundSlug/judging']['fullPath']
  >
}

interface HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugRouteRouteChildren {
  HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugConfigureRoute: typeof HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugConfigureRoute
  HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugJudgingRoute: typeof HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugJudgingRoute
}

const HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugRouteRouteChildren: HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugRouteRouteChildren =
  {
    HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugConfigureRoute:
      HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugConfigureRoute,
    HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugJudgingRoute:
      HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugJudgingRoute,
  }

const HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugRouteRouteWithChildren =
  HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugRouteRoute._addFileChildren(
    HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugRouteRouteChildren,
  )

interface HostOrgsOrgSlugCallsCallSlugRouteRouteChildren {
  HostOrgsOrgSlugCallsCallSlugDashboardRoute: typeof HostOrgsOrgSlugCallsCallSlugDashboardRoute
  HostOrgsOrgSlugCallsCallSlugEntriesRoute: typeof HostOrgsOrgSlugCallsCallSlugEntriesRoute
  HostOrgsOrgSlugCallsCallSlugTeamRoute: typeof HostOrgsOrgSlugCallsCallSlugTeamRoute
  HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugRouteRoute: typeof HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugRouteRouteWithChildren
  HostOrgsOrgSlugCallsCallSlugRoundsIndexRoute: typeof HostOrgsOrgSlugCallsCallSlugRoundsIndexRoute
}

const HostOrgsOrgSlugCallsCallSlugRouteRouteChildren: HostOrgsOrgSlugCallsCallSlugRouteRouteChildren =
  {
    HostOrgsOrgSlugCallsCallSlugDashboardRoute:
      HostOrgsOrgSlugCallsCallSlugDashboardRoute,
    HostOrgsOrgSlugCallsCallSlugEntriesRoute:
      HostOrgsOrgSlugCallsCallSlugEntriesRoute,
    HostOrgsOrgSlugCallsCallSlugTeamRoute:
      HostOrgsOrgSlugCallsCallSlugTeamRoute,
    HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugRouteRoute:
      HostOrgsOrgSlugCallsCallSlugRoundsRoundSlugRouteRouteWithChildren,
    HostOrgsOrgSlugCallsCallSlugRoundsIndexRoute:
      HostOrgsOrgSlugCallsCallSlugRoundsIndexRoute,
  }

const HostOrgsOrgSlugCallsCallSlugRouteRouteWithChildren =
  HostOrgsOrgSlugCallsCallSlugRouteRoute._addFileChildren(
    HostOrgsOrgSlugCallsCallSlugRouteRouteChildren,
  )

interface HostOrgsOrgSlugCallsRouteRouteChildren {
  HostOrgsOrgSlugCallsCallSlugRouteRoute: typeof HostOrgsOrgSlugCallsCallSlugRouteRouteWithChildren
  HostOrgsOrgSlugCallsIndexRoute: typeof HostOrgsOrgSlugCallsIndexRoute
}

const HostOrgsOrgSlugCallsRouteRouteChildren: HostOrgsOrgSlugCallsRouteRouteChildren =
  {
    HostOrgsOrgSlugCallsCallSlugRouteRoute:
      HostOrgsOrgSlugCallsCallSlugRouteRouteWithChildren,
    HostOrgsOrgSlugCallsIndexRoute: HostOrgsOrgSlugCallsIndexRoute,
  }

const HostOrgsOrgSlugCallsRouteRouteWithChildren =
  HostOrgsOrgSlugCallsRouteRoute._addFileChildren(
    HostOrgsOrgSlugCallsRouteRouteChildren,
  )

interface HostOrgsOrgSlugRouteRouteChildren {
  HostOrgsOrgSlugCallsRouteRoute: typeof HostOrgsOrgSlugCallsRouteRouteWithChildren
  HostOrgsOrgSlugMembersRoute: typeof HostOrgsOrgSlugMembersRoute
}

const HostOrgsOrgSlugRouteRouteChildren: HostOrgsOrgSlugRouteRouteChildren = {
  HostOrgsOrgSlugCallsRouteRoute: HostOrgsOrgSlugCallsRouteRouteWithChildren,
  HostOrgsOrgSlugMembersRoute: HostOrgsOrgSlugMembersRoute,
}

const HostOrgsOrgSlugRouteRouteWithChildren =
  HostOrgsOrgSlugRouteRoute._addFileChildren(HostOrgsOrgSlugRouteRouteChildren)

interface HostOrgsRouteRouteChildren {
  HostOrgsOrgSlugRouteRoute: typeof HostOrgsOrgSlugRouteRouteWithChildren
  HostOrgsNewRoute: typeof HostOrgsNewRoute
}

const HostOrgsRouteRouteChildren: HostOrgsRouteRouteChildren = {
  HostOrgsOrgSlugRouteRoute: HostOrgsOrgSlugRouteRouteWithChildren,
  HostOrgsNewRoute: HostOrgsNewRoute,
}

const HostOrgsRouteRouteWithChildren = HostOrgsRouteRoute._addFileChildren(
  HostOrgsRouteRouteChildren,
)

interface HostRouteRouteChildren {
  HostOrgsRouteRoute: typeof HostOrgsRouteRouteWithChildren
}

const HostRouteRouteChildren: HostRouteRouteChildren = {
  HostOrgsRouteRoute: HostOrgsRouteRouteWithChildren,
}

const HostRouteRouteWithChildren = HostRouteRoute._addFileChildren(
  HostRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserProfileRoute: typeof UserProfileRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserProfileRoute: UserProfileRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HostRouteRoute: HostRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
