/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/solid-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as hostHostRouteImport } from './routes/(host)/host'
import { Route as hostHostIndexRouteImport } from './routes/(host)/host.index'
import { Route as hostHostOrgsIndexRouteImport } from './routes/(host)/host.orgs.index'
import { Route as hostHostOrgsNewRouteImport } from './routes/(host)/host.orgs.new'
import { Route as hostHostOrgsOrgRouteImport } from './routes/(host)/host.orgs.$org'
import { Route as hostHostOrgsOrgIndexRouteImport } from './routes/(host)/host.orgs.$org.index'
import { Route as hostHostOrgsOrgMembersRouteImport } from './routes/(host)/host.orgs.$org.members'
import { Route as hostHostOrgsOrgCallsRouteImport } from './routes/(host)/host.orgs.$org.calls'
import { Route as hostHostOrgsOrgCallsIndexRouteImport } from './routes/(host)/host.orgs.$org.calls.index'
import { Route as hostHostOrgsOrgCallsCallRouteImport } from './routes/(host)/host.orgs.$org.calls.$call'
import { Route as hostHostOrgsOrgCallsCallEntriesRouteImport } from './routes/(host)/host.orgs.$org.calls.$call.entries'
import { Route as hostHostOrgsOrgCallsCallDashboardRouteImport } from './routes/(host)/host.orgs.$org.calls.$call.dashboard'
import { Route as hostHostOrgsOrgCallsCallRoundsIndexRouteImport } from './routes/(host)/host.orgs.$org.calls.$call.rounds.index'
import { Route as hostHostOrgsOrgCallsCallRoundsRoundJudgingRouteImport } from './routes/(host)/host.orgs.$org.calls.$call.rounds.$round.judging'
import { Route as hostHostOrgsOrgCallsCallRoundsRoundDashboardRouteImport } from './routes/(host)/host.orgs.$org.calls.$call.rounds.$round.dashboard'
import { Route as hostHostOrgsOrgCallsCallRoundsRoundConfigureRouteImport } from './routes/(host)/host.orgs.$org.calls.$call.rounds.$round.configure'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const hostHostRoute = hostHostRouteImport.update({
  id: '/(host)/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const hostHostIndexRoute = hostHostIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => hostHostRoute,
} as any)
const hostHostOrgsIndexRoute = hostHostOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => hostHostRoute,
} as any)
const hostHostOrgsNewRoute = hostHostOrgsNewRouteImport.update({
  id: '/orgs/new',
  path: '/orgs/new',
  getParentRoute: () => hostHostRoute,
} as any)
const hostHostOrgsOrgRoute = hostHostOrgsOrgRouteImport.update({
  id: '/orgs/$org',
  path: '/orgs/$org',
  getParentRoute: () => hostHostRoute,
} as any)
const hostHostOrgsOrgIndexRoute = hostHostOrgsOrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => hostHostOrgsOrgRoute,
} as any)
const hostHostOrgsOrgMembersRoute = hostHostOrgsOrgMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => hostHostOrgsOrgRoute,
} as any)
const hostHostOrgsOrgCallsRoute = hostHostOrgsOrgCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => hostHostOrgsOrgRoute,
} as any)
const hostHostOrgsOrgCallsIndexRoute =
  hostHostOrgsOrgCallsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => hostHostOrgsOrgCallsRoute,
  } as any)
const hostHostOrgsOrgCallsCallRoute =
  hostHostOrgsOrgCallsCallRouteImport.update({
    id: '/$call',
    path: '/$call',
    getParentRoute: () => hostHostOrgsOrgCallsRoute,
  } as any)
const hostHostOrgsOrgCallsCallEntriesRoute =
  hostHostOrgsOrgCallsCallEntriesRouteImport.update({
    id: '/entries',
    path: '/entries',
    getParentRoute: () => hostHostOrgsOrgCallsCallRoute,
  } as any)
const hostHostOrgsOrgCallsCallDashboardRoute =
  hostHostOrgsOrgCallsCallDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => hostHostOrgsOrgCallsCallRoute,
  } as any)
const hostHostOrgsOrgCallsCallRoundsIndexRoute =
  hostHostOrgsOrgCallsCallRoundsIndexRouteImport.update({
    id: '/rounds/',
    path: '/rounds/',
    getParentRoute: () => hostHostOrgsOrgCallsCallRoute,
  } as any)
const hostHostOrgsOrgCallsCallRoundsRoundJudgingRoute =
  hostHostOrgsOrgCallsCallRoundsRoundJudgingRouteImport.update({
    id: '/rounds/$round/judging',
    path: '/rounds/$round/judging',
    getParentRoute: () => hostHostOrgsOrgCallsCallRoute,
  } as any)
const hostHostOrgsOrgCallsCallRoundsRoundDashboardRoute =
  hostHostOrgsOrgCallsCallRoundsRoundDashboardRouteImport.update({
    id: '/rounds/$round/dashboard',
    path: '/rounds/$round/dashboard',
    getParentRoute: () => hostHostOrgsOrgCallsCallRoute,
  } as any)
const hostHostOrgsOrgCallsCallRoundsRoundConfigureRoute =
  hostHostOrgsOrgCallsCallRoundsRoundConfigureRouteImport.update({
    id: '/rounds/$round/configure',
    path: '/rounds/$round/configure',
    getParentRoute: () => hostHostOrgsOrgCallsCallRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/host': typeof hostHostRouteWithChildren
  '/host/': typeof hostHostIndexRoute
  '/host/orgs/$org': typeof hostHostOrgsOrgRouteWithChildren
  '/host/orgs/new': typeof hostHostOrgsNewRoute
  '/host/orgs': typeof hostHostOrgsIndexRoute
  '/host/orgs/$org/calls': typeof hostHostOrgsOrgCallsRouteWithChildren
  '/host/orgs/$org/members': typeof hostHostOrgsOrgMembersRoute
  '/host/orgs/$org/': typeof hostHostOrgsOrgIndexRoute
  '/host/orgs/$org/calls/$call': typeof hostHostOrgsOrgCallsCallRouteWithChildren
  '/host/orgs/$org/calls/': typeof hostHostOrgsOrgCallsIndexRoute
  '/host/orgs/$org/calls/$call/dashboard': typeof hostHostOrgsOrgCallsCallDashboardRoute
  '/host/orgs/$org/calls/$call/entries': typeof hostHostOrgsOrgCallsCallEntriesRoute
  '/host/orgs/$org/calls/$call/rounds': typeof hostHostOrgsOrgCallsCallRoundsIndexRoute
  '/host/orgs/$org/calls/$call/rounds/$round/configure': typeof hostHostOrgsOrgCallsCallRoundsRoundConfigureRoute
  '/host/orgs/$org/calls/$call/rounds/$round/dashboard': typeof hostHostOrgsOrgCallsCallRoundsRoundDashboardRoute
  '/host/orgs/$org/calls/$call/rounds/$round/judging': typeof hostHostOrgsOrgCallsCallRoundsRoundJudgingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/host': typeof hostHostIndexRoute
  '/host/orgs/new': typeof hostHostOrgsNewRoute
  '/host/orgs': typeof hostHostOrgsIndexRoute
  '/host/orgs/$org/members': typeof hostHostOrgsOrgMembersRoute
  '/host/orgs/$org': typeof hostHostOrgsOrgIndexRoute
  '/host/orgs/$org/calls/$call': typeof hostHostOrgsOrgCallsCallRouteWithChildren
  '/host/orgs/$org/calls': typeof hostHostOrgsOrgCallsIndexRoute
  '/host/orgs/$org/calls/$call/dashboard': typeof hostHostOrgsOrgCallsCallDashboardRoute
  '/host/orgs/$org/calls/$call/entries': typeof hostHostOrgsOrgCallsCallEntriesRoute
  '/host/orgs/$org/calls/$call/rounds': typeof hostHostOrgsOrgCallsCallRoundsIndexRoute
  '/host/orgs/$org/calls/$call/rounds/$round/configure': typeof hostHostOrgsOrgCallsCallRoundsRoundConfigureRoute
  '/host/orgs/$org/calls/$call/rounds/$round/dashboard': typeof hostHostOrgsOrgCallsCallRoundsRoundDashboardRoute
  '/host/orgs/$org/calls/$call/rounds/$round/judging': typeof hostHostOrgsOrgCallsCallRoundsRoundJudgingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/(host)/host': typeof hostHostRouteWithChildren
  '/(host)/host/': typeof hostHostIndexRoute
  '/(host)/host/orgs/$org': typeof hostHostOrgsOrgRouteWithChildren
  '/(host)/host/orgs/new': typeof hostHostOrgsNewRoute
  '/(host)/host/orgs/': typeof hostHostOrgsIndexRoute
  '/(host)/host/orgs/$org/calls': typeof hostHostOrgsOrgCallsRouteWithChildren
  '/(host)/host/orgs/$org/members': typeof hostHostOrgsOrgMembersRoute
  '/(host)/host/orgs/$org/': typeof hostHostOrgsOrgIndexRoute
  '/(host)/host/orgs/$org/calls/$call': typeof hostHostOrgsOrgCallsCallRouteWithChildren
  '/(host)/host/orgs/$org/calls/': typeof hostHostOrgsOrgCallsIndexRoute
  '/(host)/host/orgs/$org/calls/$call/dashboard': typeof hostHostOrgsOrgCallsCallDashboardRoute
  '/(host)/host/orgs/$org/calls/$call/entries': typeof hostHostOrgsOrgCallsCallEntriesRoute
  '/(host)/host/orgs/$org/calls/$call/rounds/': typeof hostHostOrgsOrgCallsCallRoundsIndexRoute
  '/(host)/host/orgs/$org/calls/$call/rounds/$round/configure': typeof hostHostOrgsOrgCallsCallRoundsRoundConfigureRoute
  '/(host)/host/orgs/$org/calls/$call/rounds/$round/dashboard': typeof hostHostOrgsOrgCallsCallRoundsRoundDashboardRoute
  '/(host)/host/orgs/$org/calls/$call/rounds/$round/judging': typeof hostHostOrgsOrgCallsCallRoundsRoundJudgingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/host'
    | '/host/'
    | '/host/orgs/$org'
    | '/host/orgs/new'
    | '/host/orgs'
    | '/host/orgs/$org/calls'
    | '/host/orgs/$org/members'
    | '/host/orgs/$org/'
    | '/host/orgs/$org/calls/$call'
    | '/host/orgs/$org/calls/'
    | '/host/orgs/$org/calls/$call/dashboard'
    | '/host/orgs/$org/calls/$call/entries'
    | '/host/orgs/$org/calls/$call/rounds'
    | '/host/orgs/$org/calls/$call/rounds/$round/configure'
    | '/host/orgs/$org/calls/$call/rounds/$round/dashboard'
    | '/host/orgs/$org/calls/$call/rounds/$round/judging'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/host'
    | '/host/orgs/new'
    | '/host/orgs'
    | '/host/orgs/$org/members'
    | '/host/orgs/$org'
    | '/host/orgs/$org/calls/$call'
    | '/host/orgs/$org/calls'
    | '/host/orgs/$org/calls/$call/dashboard'
    | '/host/orgs/$org/calls/$call/entries'
    | '/host/orgs/$org/calls/$call/rounds'
    | '/host/orgs/$org/calls/$call/rounds/$round/configure'
    | '/host/orgs/$org/calls/$call/rounds/$round/dashboard'
    | '/host/orgs/$org/calls/$call/rounds/$round/judging'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/(host)/host'
    | '/(host)/host/'
    | '/(host)/host/orgs/$org'
    | '/(host)/host/orgs/new'
    | '/(host)/host/orgs/'
    | '/(host)/host/orgs/$org/calls'
    | '/(host)/host/orgs/$org/members'
    | '/(host)/host/orgs/$org/'
    | '/(host)/host/orgs/$org/calls/$call'
    | '/(host)/host/orgs/$org/calls/'
    | '/(host)/host/orgs/$org/calls/$call/dashboard'
    | '/(host)/host/orgs/$org/calls/$call/entries'
    | '/(host)/host/orgs/$org/calls/$call/rounds/'
    | '/(host)/host/orgs/$org/calls/$call/rounds/$round/configure'
    | '/(host)/host/orgs/$org/calls/$call/rounds/$round/dashboard'
    | '/(host)/host/orgs/$org/calls/$call/rounds/$round/judging'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  hostHostRoute: typeof hostHostRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(host)/host': {
      id: '/(host)/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof hostHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(host)/host/': {
      id: '/(host)/host/'
      path: '/'
      fullPath: '/host/'
      preLoaderRoute: typeof hostHostIndexRouteImport
      parentRoute: typeof hostHostRoute
    }
    '/(host)/host/orgs/$org': {
      id: '/(host)/host/orgs/$org'
      path: '/orgs/$org'
      fullPath: '/host/orgs/$org'
      preLoaderRoute: typeof hostHostOrgsOrgRouteImport
      parentRoute: typeof hostHostRoute
    }
    '/(host)/host/orgs/new': {
      id: '/(host)/host/orgs/new'
      path: '/orgs/new'
      fullPath: '/host/orgs/new'
      preLoaderRoute: typeof hostHostOrgsNewRouteImport
      parentRoute: typeof hostHostRoute
    }
    '/(host)/host/orgs/': {
      id: '/(host)/host/orgs/'
      path: '/orgs'
      fullPath: '/host/orgs'
      preLoaderRoute: typeof hostHostOrgsIndexRouteImport
      parentRoute: typeof hostHostRoute
    }
    '/(host)/host/orgs/$org/calls': {
      id: '/(host)/host/orgs/$org/calls'
      path: '/calls'
      fullPath: '/host/orgs/$org/calls'
      preLoaderRoute: typeof hostHostOrgsOrgCallsRouteImport
      parentRoute: typeof hostHostOrgsOrgRoute
    }
    '/(host)/host/orgs/$org/members': {
      id: '/(host)/host/orgs/$org/members'
      path: '/members'
      fullPath: '/host/orgs/$org/members'
      preLoaderRoute: typeof hostHostOrgsOrgMembersRouteImport
      parentRoute: typeof hostHostOrgsOrgRoute
    }
    '/(host)/host/orgs/$org/': {
      id: '/(host)/host/orgs/$org/'
      path: '/'
      fullPath: '/host/orgs/$org/'
      preLoaderRoute: typeof hostHostOrgsOrgIndexRouteImport
      parentRoute: typeof hostHostOrgsOrgRoute
    }
    '/(host)/host/orgs/$org/calls/$call': {
      id: '/(host)/host/orgs/$org/calls/$call'
      path: '/$call'
      fullPath: '/host/orgs/$org/calls/$call'
      preLoaderRoute: typeof hostHostOrgsOrgCallsCallRouteImport
      parentRoute: typeof hostHostOrgsOrgCallsRoute
    }
    '/(host)/host/orgs/$org/calls/': {
      id: '/(host)/host/orgs/$org/calls/'
      path: '/'
      fullPath: '/host/orgs/$org/calls/'
      preLoaderRoute: typeof hostHostOrgsOrgCallsIndexRouteImport
      parentRoute: typeof hostHostOrgsOrgCallsRoute
    }
    '/(host)/host/orgs/$org/calls/$call/dashboard': {
      id: '/(host)/host/orgs/$org/calls/$call/dashboard'
      path: '/dashboard'
      fullPath: '/host/orgs/$org/calls/$call/dashboard'
      preLoaderRoute: typeof hostHostOrgsOrgCallsCallDashboardRouteImport
      parentRoute: typeof hostHostOrgsOrgCallsCallRoute
    }
    '/(host)/host/orgs/$org/calls/$call/entries': {
      id: '/(host)/host/orgs/$org/calls/$call/entries'
      path: '/entries'
      fullPath: '/host/orgs/$org/calls/$call/entries'
      preLoaderRoute: typeof hostHostOrgsOrgCallsCallEntriesRouteImport
      parentRoute: typeof hostHostOrgsOrgCallsCallRoute
    }
    '/(host)/host/orgs/$org/calls/$call/rounds/': {
      id: '/(host)/host/orgs/$org/calls/$call/rounds/'
      path: '/rounds'
      fullPath: '/host/orgs/$org/calls/$call/rounds'
      preLoaderRoute: typeof hostHostOrgsOrgCallsCallRoundsIndexRouteImport
      parentRoute: typeof hostHostOrgsOrgCallsCallRoute
    }
    '/(host)/host/orgs/$org/calls/$call/rounds/$round/configure': {
      id: '/(host)/host/orgs/$org/calls/$call/rounds/$round/configure'
      path: '/rounds/$round/configure'
      fullPath: '/host/orgs/$org/calls/$call/rounds/$round/configure'
      preLoaderRoute: typeof hostHostOrgsOrgCallsCallRoundsRoundConfigureRouteImport
      parentRoute: typeof hostHostOrgsOrgCallsCallRoute
    }
    '/(host)/host/orgs/$org/calls/$call/rounds/$round/dashboard': {
      id: '/(host)/host/orgs/$org/calls/$call/rounds/$round/dashboard'
      path: '/rounds/$round/dashboard'
      fullPath: '/host/orgs/$org/calls/$call/rounds/$round/dashboard'
      preLoaderRoute: typeof hostHostOrgsOrgCallsCallRoundsRoundDashboardRouteImport
      parentRoute: typeof hostHostOrgsOrgCallsCallRoute
    }
    '/(host)/host/orgs/$org/calls/$call/rounds/$round/judging': {
      id: '/(host)/host/orgs/$org/calls/$call/rounds/$round/judging'
      path: '/rounds/$round/judging'
      fullPath: '/host/orgs/$org/calls/$call/rounds/$round/judging'
      preLoaderRoute: typeof hostHostOrgsOrgCallsCallRoundsRoundJudgingRouteImport
      parentRoute: typeof hostHostOrgsOrgCallsCallRoute
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/login' {
  const createFileRoute: CreateFileRoute<
    '/login',
    FileRoutesByPath['/login']['parentRoute'],
    FileRoutesByPath['/login']['id'],
    FileRoutesByPath['/login']['path'],
    FileRoutesByPath['/login']['fullPath']
  >
}
declare module './routes/(host)/host' {
  const createFileRoute: CreateFileRoute<
    '/(host)/host',
    FileRoutesByPath['/(host)/host']['parentRoute'],
    FileRoutesByPath['/(host)/host']['id'],
    FileRoutesByPath['/(host)/host']['path'],
    FileRoutesByPath['/(host)/host']['fullPath']
  >
}
declare module './routes/(host)/host.index' {
  const createFileRoute: CreateFileRoute<
    '/(host)/host/',
    FileRoutesByPath['/(host)/host/']['parentRoute'],
    FileRoutesByPath['/(host)/host/']['id'],
    FileRoutesByPath['/(host)/host/']['path'],
    FileRoutesByPath['/(host)/host/']['fullPath']
  >
}
declare module './routes/(host)/host.orgs.$org' {
  const createFileRoute: CreateFileRoute<
    '/(host)/host/orgs/$org',
    FileRoutesByPath['/(host)/host/orgs/$org']['parentRoute'],
    FileRoutesByPath['/(host)/host/orgs/$org']['id'],
    FileRoutesByPath['/(host)/host/orgs/$org']['path'],
    FileRoutesByPath['/(host)/host/orgs/$org']['fullPath']
  >
}
declare module './routes/(host)/host.orgs.new' {
  const createFileRoute: CreateFileRoute<
    '/(host)/host/orgs/new',
    FileRoutesByPath['/(host)/host/orgs/new']['parentRoute'],
    FileRoutesByPath['/(host)/host/orgs/new']['id'],
    FileRoutesByPath['/(host)/host/orgs/new']['path'],
    FileRoutesByPath['/(host)/host/orgs/new']['fullPath']
  >
}
declare module './routes/(host)/host.orgs.index' {
  const createFileRoute: CreateFileRoute<
    '/(host)/host/orgs/',
    FileRoutesByPath['/(host)/host/orgs/']['parentRoute'],
    FileRoutesByPath['/(host)/host/orgs/']['id'],
    FileRoutesByPath['/(host)/host/orgs/']['path'],
    FileRoutesByPath['/(host)/host/orgs/']['fullPath']
  >
}
declare module './routes/(host)/host.orgs.$org.calls' {
  const createFileRoute: CreateFileRoute<
    '/(host)/host/orgs/$org/calls',
    FileRoutesByPath['/(host)/host/orgs/$org/calls']['parentRoute'],
    FileRoutesByPath['/(host)/host/orgs/$org/calls']['id'],
    FileRoutesByPath['/(host)/host/orgs/$org/calls']['path'],
    FileRoutesByPath['/(host)/host/orgs/$org/calls']['fullPath']
  >
}
declare module './routes/(host)/host.orgs.$org.members' {
  const createFileRoute: CreateFileRoute<
    '/(host)/host/orgs/$org/members',
    FileRoutesByPath['/(host)/host/orgs/$org/members']['parentRoute'],
    FileRoutesByPath['/(host)/host/orgs/$org/members']['id'],
    FileRoutesByPath['/(host)/host/orgs/$org/members']['path'],
    FileRoutesByPath['/(host)/host/orgs/$org/members']['fullPath']
  >
}
declare module './routes/(host)/host.orgs.$org.index' {
  const createFileRoute: CreateFileRoute<
    '/(host)/host/orgs/$org/',
    FileRoutesByPath['/(host)/host/orgs/$org/']['parentRoute'],
    FileRoutesByPath['/(host)/host/orgs/$org/']['id'],
    FileRoutesByPath['/(host)/host/orgs/$org/']['path'],
    FileRoutesByPath['/(host)/host/orgs/$org/']['fullPath']
  >
}
declare module './routes/(host)/host.orgs.$org.calls.$call' {
  const createFileRoute: CreateFileRoute<
    '/(host)/host/orgs/$org/calls/$call',
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call']['parentRoute'],
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call']['id'],
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call']['path'],
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call']['fullPath']
  >
}
declare module './routes/(host)/host.orgs.$org.calls.index' {
  const createFileRoute: CreateFileRoute<
    '/(host)/host/orgs/$org/calls/',
    FileRoutesByPath['/(host)/host/orgs/$org/calls/']['parentRoute'],
    FileRoutesByPath['/(host)/host/orgs/$org/calls/']['id'],
    FileRoutesByPath['/(host)/host/orgs/$org/calls/']['path'],
    FileRoutesByPath['/(host)/host/orgs/$org/calls/']['fullPath']
  >
}
declare module './routes/(host)/host.orgs.$org.calls.$call.dashboard' {
  const createFileRoute: CreateFileRoute<
    '/(host)/host/orgs/$org/calls/$call/dashboard',
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call/dashboard']['parentRoute'],
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call/dashboard']['id'],
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call/dashboard']['path'],
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call/dashboard']['fullPath']
  >
}
declare module './routes/(host)/host.orgs.$org.calls.$call.entries' {
  const createFileRoute: CreateFileRoute<
    '/(host)/host/orgs/$org/calls/$call/entries',
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call/entries']['parentRoute'],
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call/entries']['id'],
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call/entries']['path'],
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call/entries']['fullPath']
  >
}
declare module './routes/(host)/host.orgs.$org.calls.$call.rounds.index' {
  const createFileRoute: CreateFileRoute<
    '/(host)/host/orgs/$org/calls/$call/rounds/',
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call/rounds/']['parentRoute'],
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call/rounds/']['id'],
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call/rounds/']['path'],
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call/rounds/']['fullPath']
  >
}
declare module './routes/(host)/host.orgs.$org.calls.$call.rounds.$round.configure' {
  const createFileRoute: CreateFileRoute<
    '/(host)/host/orgs/$org/calls/$call/rounds/$round/configure',
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call/rounds/$round/configure']['parentRoute'],
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call/rounds/$round/configure']['id'],
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call/rounds/$round/configure']['path'],
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call/rounds/$round/configure']['fullPath']
  >
}
declare module './routes/(host)/host.orgs.$org.calls.$call.rounds.$round.dashboard' {
  const createFileRoute: CreateFileRoute<
    '/(host)/host/orgs/$org/calls/$call/rounds/$round/dashboard',
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call/rounds/$round/dashboard']['parentRoute'],
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call/rounds/$round/dashboard']['id'],
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call/rounds/$round/dashboard']['path'],
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call/rounds/$round/dashboard']['fullPath']
  >
}
declare module './routes/(host)/host.orgs.$org.calls.$call.rounds.$round.judging' {
  const createFileRoute: CreateFileRoute<
    '/(host)/host/orgs/$org/calls/$call/rounds/$round/judging',
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call/rounds/$round/judging']['parentRoute'],
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call/rounds/$round/judging']['id'],
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call/rounds/$round/judging']['path'],
    FileRoutesByPath['/(host)/host/orgs/$org/calls/$call/rounds/$round/judging']['fullPath']
  >
}

interface hostHostOrgsOrgCallsCallRouteChildren {
  hostHostOrgsOrgCallsCallDashboardRoute: typeof hostHostOrgsOrgCallsCallDashboardRoute
  hostHostOrgsOrgCallsCallEntriesRoute: typeof hostHostOrgsOrgCallsCallEntriesRoute
  hostHostOrgsOrgCallsCallRoundsIndexRoute: typeof hostHostOrgsOrgCallsCallRoundsIndexRoute
  hostHostOrgsOrgCallsCallRoundsRoundConfigureRoute: typeof hostHostOrgsOrgCallsCallRoundsRoundConfigureRoute
  hostHostOrgsOrgCallsCallRoundsRoundDashboardRoute: typeof hostHostOrgsOrgCallsCallRoundsRoundDashboardRoute
  hostHostOrgsOrgCallsCallRoundsRoundJudgingRoute: typeof hostHostOrgsOrgCallsCallRoundsRoundJudgingRoute
}

const hostHostOrgsOrgCallsCallRouteChildren: hostHostOrgsOrgCallsCallRouteChildren =
  {
    hostHostOrgsOrgCallsCallDashboardRoute:
      hostHostOrgsOrgCallsCallDashboardRoute,
    hostHostOrgsOrgCallsCallEntriesRoute: hostHostOrgsOrgCallsCallEntriesRoute,
    hostHostOrgsOrgCallsCallRoundsIndexRoute:
      hostHostOrgsOrgCallsCallRoundsIndexRoute,
    hostHostOrgsOrgCallsCallRoundsRoundConfigureRoute:
      hostHostOrgsOrgCallsCallRoundsRoundConfigureRoute,
    hostHostOrgsOrgCallsCallRoundsRoundDashboardRoute:
      hostHostOrgsOrgCallsCallRoundsRoundDashboardRoute,
    hostHostOrgsOrgCallsCallRoundsRoundJudgingRoute:
      hostHostOrgsOrgCallsCallRoundsRoundJudgingRoute,
  }

const hostHostOrgsOrgCallsCallRouteWithChildren =
  hostHostOrgsOrgCallsCallRoute._addFileChildren(
    hostHostOrgsOrgCallsCallRouteChildren,
  )

interface hostHostOrgsOrgCallsRouteChildren {
  hostHostOrgsOrgCallsCallRoute: typeof hostHostOrgsOrgCallsCallRouteWithChildren
  hostHostOrgsOrgCallsIndexRoute: typeof hostHostOrgsOrgCallsIndexRoute
}

const hostHostOrgsOrgCallsRouteChildren: hostHostOrgsOrgCallsRouteChildren = {
  hostHostOrgsOrgCallsCallRoute: hostHostOrgsOrgCallsCallRouteWithChildren,
  hostHostOrgsOrgCallsIndexRoute: hostHostOrgsOrgCallsIndexRoute,
}

const hostHostOrgsOrgCallsRouteWithChildren =
  hostHostOrgsOrgCallsRoute._addFileChildren(hostHostOrgsOrgCallsRouteChildren)

interface hostHostOrgsOrgRouteChildren {
  hostHostOrgsOrgCallsRoute: typeof hostHostOrgsOrgCallsRouteWithChildren
  hostHostOrgsOrgMembersRoute: typeof hostHostOrgsOrgMembersRoute
  hostHostOrgsOrgIndexRoute: typeof hostHostOrgsOrgIndexRoute
}

const hostHostOrgsOrgRouteChildren: hostHostOrgsOrgRouteChildren = {
  hostHostOrgsOrgCallsRoute: hostHostOrgsOrgCallsRouteWithChildren,
  hostHostOrgsOrgMembersRoute: hostHostOrgsOrgMembersRoute,
  hostHostOrgsOrgIndexRoute: hostHostOrgsOrgIndexRoute,
}

const hostHostOrgsOrgRouteWithChildren = hostHostOrgsOrgRoute._addFileChildren(
  hostHostOrgsOrgRouteChildren,
)

interface hostHostRouteChildren {
  hostHostIndexRoute: typeof hostHostIndexRoute
  hostHostOrgsOrgRoute: typeof hostHostOrgsOrgRouteWithChildren
  hostHostOrgsNewRoute: typeof hostHostOrgsNewRoute
  hostHostOrgsIndexRoute: typeof hostHostOrgsIndexRoute
}

const hostHostRouteChildren: hostHostRouteChildren = {
  hostHostIndexRoute: hostHostIndexRoute,
  hostHostOrgsOrgRoute: hostHostOrgsOrgRouteWithChildren,
  hostHostOrgsNewRoute: hostHostOrgsNewRoute,
  hostHostOrgsIndexRoute: hostHostOrgsIndexRoute,
}

const hostHostRouteWithChildren = hostHostRoute._addFileChildren(
  hostHostRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  hostHostRoute: hostHostRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
